version: 0.2

phases:
  pre_build:
    commands:
      - echo "Reading image tag from previous stage..."
      - IMAGE_TAG=$(cat imageDetail.txt)
      - echo "Image tag: $IMAGE_TAG"
      - REPOSITORY_URI=387158738266.dkr.ecr.us-east-2.amazonaws.com/product-catalog
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo "Starting container for integration tests..."
      - docker run -d --name product-catalog -p 8080:8080 $REPOSITORY_URI:$IMAGE_TAG
      - echo "Waiting for application to start..."
      - sleep 20
      - echo "Running integration tests..."
      - mvn verify -Pintegration-tests
  post_build:
    commands:
      - echo "Stopping and removing test container..."
      - docker stop product-catalog
      - docker rm product-catalog
